<?php

declare(strict_types=1);

/*
 * GCAPIForESTLabLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GCAPIForESTLabLib\Models;

use stdClass;

class Entry implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $representative;

    /**
     * @var string|null
     */
    private $territoryNumber;

    /**
     * @var string|null
     */
    private $samplingDate;

    /**
     * @var string|null
     */
    private $time;

    /**
     * @var string|null
     */
    private $reportTo;

    /**
     * @var string|null
     */
    private $poNumber;

    /**
     * @var string|null
     */
    private $customerNumber;

    /**
     * @var string|null
     */
    private $customerName;

    /**
     * @var string|null
     */
    private $laboratoryEmail;

    /**
     * @var string|null
     */
    private $address;

    /**
     * @var Sample[]|null
     */
    private $samples;

    /**
     * @var string[]|null
     */
    private $analysis;

    /**
     * @var string|null
     */
    private $notes;

    /**
     * @var string|null
     */
    private $laboratoryResultsFile;

    /**
     * Returns Representative.
     */
    public function getRepresentative(): ?string
    {
        return $this->representative;
    }

    /**
     * Sets Representative.
     *
     * @maps representative
     */
    public function setRepresentative(?string $representative): void
    {
        $this->representative = $representative;
    }

    /**
     * Returns Territory Number.
     */
    public function getTerritoryNumber(): ?string
    {
        return $this->territoryNumber;
    }

    /**
     * Sets Territory Number.
     *
     * @maps territory_number
     */
    public function setTerritoryNumber(?string $territoryNumber): void
    {
        $this->territoryNumber = $territoryNumber;
    }

    /**
     * Returns Sampling Date.
     */
    public function getSamplingDate(): ?string
    {
        return $this->samplingDate;
    }

    /**
     * Sets Sampling Date.
     *
     * @maps sampling_date
     */
    public function setSamplingDate(?string $samplingDate): void
    {
        $this->samplingDate = $samplingDate;
    }

    /**
     * Returns Time.
     */
    public function getTime(): ?string
    {
        return $this->time;
    }

    /**
     * Sets Time.
     *
     * @maps time
     */
    public function setTime(?string $time): void
    {
        $this->time = $time;
    }

    /**
     * Returns Report To.
     */
    public function getReportTo(): ?string
    {
        return $this->reportTo;
    }

    /**
     * Sets Report To.
     *
     * @maps report_to
     */
    public function setReportTo(?string $reportTo): void
    {
        $this->reportTo = $reportTo;
    }

    /**
     * Returns Po Number.
     */
    public function getPoNumber(): ?string
    {
        return $this->poNumber;
    }

    /**
     * Sets Po Number.
     *
     * @maps po_number
     */
    public function setPoNumber(?string $poNumber): void
    {
        $this->poNumber = $poNumber;
    }

    /**
     * Returns Customer Number.
     */
    public function getCustomerNumber(): ?string
    {
        return $this->customerNumber;
    }

    /**
     * Sets Customer Number.
     *
     * @maps customer_number
     */
    public function setCustomerNumber(?string $customerNumber): void
    {
        $this->customerNumber = $customerNumber;
    }

    /**
     * Returns Customer Name.
     */
    public function getCustomerName(): ?string
    {
        return $this->customerName;
    }

    /**
     * Sets Customer Name.
     *
     * @maps customer_name
     */
    public function setCustomerName(?string $customerName): void
    {
        $this->customerName = $customerName;
    }

    /**
     * Returns Laboratory Email.
     */
    public function getLaboratoryEmail(): ?string
    {
        return $this->laboratoryEmail;
    }

    /**
     * Sets Laboratory Email.
     *
     * @maps laboratory_email
     */
    public function setLaboratoryEmail(?string $laboratoryEmail): void
    {
        $this->laboratoryEmail = $laboratoryEmail;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @maps address
     */
    public function setAddress(?string $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Samples.
     *
     * @return Sample[]|null
     */
    public function getSamples(): ?array
    {
        return $this->samples;
    }

    /**
     * Sets Samples.
     *
     * @maps samples
     *
     * @param Sample[]|null $samples
     */
    public function setSamples(?array $samples): void
    {
        $this->samples = $samples;
    }

    /**
     * Returns Analysis.
     *
     * @return string[]|null
     */
    public function getAnalysis(): ?array
    {
        return $this->analysis;
    }

    /**
     * Sets Analysis.
     *
     * @maps analysis
     *
     * @param string[]|null $analysis
     */
    public function setAnalysis(?array $analysis): void
    {
        $this->analysis = $analysis;
    }

    /**
     * Returns Notes.
     */
    public function getNotes(): ?string
    {
        return $this->notes;
    }

    /**
     * Sets Notes.
     *
     * @maps notes
     */
    public function setNotes(?string $notes): void
    {
        $this->notes = $notes;
    }

    /**
     * Returns Laboratory Results File.
     */
    public function getLaboratoryResultsFile(): ?string
    {
        return $this->laboratoryResultsFile;
    }

    /**
     * Sets Laboratory Results File.
     *
     * @maps laboratory_results_file
     */
    public function setLaboratoryResultsFile(?string $laboratoryResultsFile): void
    {
        $this->laboratoryResultsFile = $laboratoryResultsFile;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->representative)) {
            $json['representative']          = $this->representative;
        }
        if (isset($this->territoryNumber)) {
            $json['territory_number']        = $this->territoryNumber;
        }
        if (isset($this->samplingDate)) {
            $json['sampling_date']           = $this->samplingDate;
        }
        if (isset($this->time)) {
            $json['time']                    = $this->time;
        }
        if (isset($this->reportTo)) {
            $json['report_to']               = $this->reportTo;
        }
        if (isset($this->poNumber)) {
            $json['po_number']               = $this->poNumber;
        }
        if (isset($this->customerNumber)) {
            $json['customer_number']         = $this->customerNumber;
        }
        if (isset($this->customerName)) {
            $json['customer_name']           = $this->customerName;
        }
        if (isset($this->laboratoryEmail)) {
            $json['laboratory_email']        = $this->laboratoryEmail;
        }
        if (isset($this->address)) {
            $json['address']                 = $this->address;
        }
        if (isset($this->samples)) {
            $json['samples']                 = $this->samples;
        }
        if (isset($this->analysis)) {
            $json['analysis']                = $this->analysis;
        }
        if (isset($this->notes)) {
            $json['notes']                   = $this->notes;
        }
        if (isset($this->laboratoryResultsFile)) {
            $json['laboratory_results_file'] = $this->laboratoryResultsFile;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
