<?php

declare(strict_types=1);

/*
 * GCAPIForESTLabLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace GCAPIForESTLabLib\Models;

use stdClass;

class Sample implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $date;

    /**
     * @var string|null
     */
    private $sampleNumber;

    /**
     * @var string|null
     */
    private $sampleCategory;

    /**
     * @var string|null
     */
    private $roomLocation;

    /**
     * @var string|null
     */
    private $equipmentType;

    /**
     * @var string|null
     */
    private $faucetDescription;

    /**
     * @var string|null
     */
    private $aeratorFilter;

    /**
     * @var string|null
     */
    private $maxTemp;

    /**
     * @var string|null
     */
    private $timeToTemp;

    /**
     * @var string|null
     */
    private $sampleTime;

    /**
     * @var string|null
     */
    private $legionellaSg1;

    /**
     * @var string|null
     */
    private $legionellaSg2;

    /**
     * @var string|null
     */
    private $nonPneumophilaLegionella;

    /**
     * @var string|null
     */
    private $totalLegionella;

    /**
     * @var string|null
     */
    private $hpc;

    /**
     * @var string|null
     */
    private $notes;

    /**
     * Returns Date.
     */
    public function getDate(): ?string
    {
        return $this->date;
    }

    /**
     * Sets Date.
     *
     * @maps date
     */
    public function setDate(?string $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Sample Number.
     */
    public function getSampleNumber(): ?string
    {
        return $this->sampleNumber;
    }

    /**
     * Sets Sample Number.
     *
     * @maps sample_number
     */
    public function setSampleNumber(?string $sampleNumber): void
    {
        $this->sampleNumber = $sampleNumber;
    }

    /**
     * Returns Sample Category.
     */
    public function getSampleCategory(): ?string
    {
        return $this->sampleCategory;
    }

    /**
     * Sets Sample Category.
     *
     * @maps sample_category
     */
    public function setSampleCategory(?string $sampleCategory): void
    {
        $this->sampleCategory = $sampleCategory;
    }

    /**
     * Returns Room Location.
     */
    public function getRoomLocation(): ?string
    {
        return $this->roomLocation;
    }

    /**
     * Sets Room Location.
     *
     * @maps room_location
     */
    public function setRoomLocation(?string $roomLocation): void
    {
        $this->roomLocation = $roomLocation;
    }

    /**
     * Returns Equipment Type.
     */
    public function getEquipmentType(): ?string
    {
        return $this->equipmentType;
    }

    /**
     * Sets Equipment Type.
     *
     * @maps equipment_type
     */
    public function setEquipmentType(?string $equipmentType): void
    {
        $this->equipmentType = $equipmentType;
    }

    /**
     * Returns Faucet Description.
     */
    public function getFaucetDescription(): ?string
    {
        return $this->faucetDescription;
    }

    /**
     * Sets Faucet Description.
     *
     * @maps faucet_description
     */
    public function setFaucetDescription(?string $faucetDescription): void
    {
        $this->faucetDescription = $faucetDescription;
    }

    /**
     * Returns Aerator Filter.
     */
    public function getAeratorFilter(): ?string
    {
        return $this->aeratorFilter;
    }

    /**
     * Sets Aerator Filter.
     *
     * @maps aerator_filter
     */
    public function setAeratorFilter(?string $aeratorFilter): void
    {
        $this->aeratorFilter = $aeratorFilter;
    }

    /**
     * Returns Max Temp.
     */
    public function getMaxTemp(): ?string
    {
        return $this->maxTemp;
    }

    /**
     * Sets Max Temp.
     *
     * @maps max_temp
     */
    public function setMaxTemp(?string $maxTemp): void
    {
        $this->maxTemp = $maxTemp;
    }

    /**
     * Returns Time to Temp.
     */
    public function getTimeToTemp(): ?string
    {
        return $this->timeToTemp;
    }

    /**
     * Sets Time to Temp.
     *
     * @maps time_to_temp
     */
    public function setTimeToTemp(?string $timeToTemp): void
    {
        $this->timeToTemp = $timeToTemp;
    }

    /**
     * Returns Sample Time.
     */
    public function getSampleTime(): ?string
    {
        return $this->sampleTime;
    }

    /**
     * Sets Sample Time.
     *
     * @maps sample_time
     */
    public function setSampleTime(?string $sampleTime): void
    {
        $this->sampleTime = $sampleTime;
    }

    /**
     * Returns Legionella Sg 1.
     */
    public function getLegionellaSg1(): ?string
    {
        return $this->legionellaSg1;
    }

    /**
     * Sets Legionella Sg 1.
     *
     * @maps legionella_sg1
     */
    public function setLegionellaSg1(?string $legionellaSg1): void
    {
        $this->legionellaSg1 = $legionellaSg1;
    }

    /**
     * Returns Legionella Sg 2.
     */
    public function getLegionellaSg2(): ?string
    {
        return $this->legionellaSg2;
    }

    /**
     * Sets Legionella Sg 2.
     *
     * @maps legionella_sg2
     */
    public function setLegionellaSg2(?string $legionellaSg2): void
    {
        $this->legionellaSg2 = $legionellaSg2;
    }

    /**
     * Returns Non Pneumophila Legionella.
     */
    public function getNonPneumophilaLegionella(): ?string
    {
        return $this->nonPneumophilaLegionella;
    }

    /**
     * Sets Non Pneumophila Legionella.
     *
     * @maps non_pneumophila_legionella
     */
    public function setNonPneumophilaLegionella(?string $nonPneumophilaLegionella): void
    {
        $this->nonPneumophilaLegionella = $nonPneumophilaLegionella;
    }

    /**
     * Returns Total Legionella.
     */
    public function getTotalLegionella(): ?string
    {
        return $this->totalLegionella;
    }

    /**
     * Sets Total Legionella.
     *
     * @maps total_legionella
     */
    public function setTotalLegionella(?string $totalLegionella): void
    {
        $this->totalLegionella = $totalLegionella;
    }

    /**
     * Returns Hpc.
     */
    public function getHpc(): ?string
    {
        return $this->hpc;
    }

    /**
     * Sets Hpc.
     *
     * @maps hpc
     */
    public function setHpc(?string $hpc): void
    {
        $this->hpc = $hpc;
    }

    /**
     * Returns Notes.
     */
    public function getNotes(): ?string
    {
        return $this->notes;
    }

    /**
     * Sets Notes.
     *
     * @maps notes
     */
    public function setNotes(?string $notes): void
    {
        $this->notes = $notes;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->date)) {
            $json['date']                       = $this->date;
        }
        if (isset($this->sampleNumber)) {
            $json['sample_number']              = $this->sampleNumber;
        }
        if (isset($this->sampleCategory)) {
            $json['sample_category']            = $this->sampleCategory;
        }
        if (isset($this->roomLocation)) {
            $json['room_location']              = $this->roomLocation;
        }
        if (isset($this->equipmentType)) {
            $json['equipment_type']             = $this->equipmentType;
        }
        if (isset($this->faucetDescription)) {
            $json['faucet_description']         = $this->faucetDescription;
        }
        if (isset($this->aeratorFilter)) {
            $json['aerator_filter']             = $this->aeratorFilter;
        }
        if (isset($this->maxTemp)) {
            $json['max_temp']                   = $this->maxTemp;
        }
        if (isset($this->timeToTemp)) {
            $json['time_to_temp']               = $this->timeToTemp;
        }
        if (isset($this->sampleTime)) {
            $json['sample_time']                = $this->sampleTime;
        }
        if (isset($this->legionellaSg1)) {
            $json['legionella_sg1']             = $this->legionellaSg1;
        }
        if (isset($this->legionellaSg2)) {
            $json['legionella_sg2']             = $this->legionellaSg2;
        }
        if (isset($this->nonPneumophilaLegionella)) {
            $json['non_pneumophila_legionella'] = $this->nonPneumophilaLegionella;
        }
        if (isset($this->totalLegionella)) {
            $json['total_legionella']           = $this->totalLegionella;
        }
        if (isset($this->hpc)) {
            $json['hpc']                        = $this->hpc;
        }
        if (isset($this->notes)) {
            $json['notes']                      = $this->notes;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
